In [7]:
import torch

print(torch.empty(2,3))
print(torch.rand(3,4))
print(torch.randn(2, 3))
print(torch.zeros(3,4,dtype=torch.long))
print(torch.zeros(3,4,dtype=torch.double))
print(torch.arange(1,10,2))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.9573, 0.2852, 0.6825, 0.2432],
        [0.0230, 0.9166, 0.0353, 0.0446],
        [0.3484, 0.4162, 0.4160, 0.5381]])
tensor([[ 2.0802,  0.0605, -2.5386],
        [ 0.5451,  0.7102,  0.6108]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)
tensor([1, 3, 5, 7, 9])


In [11]:
array = [[1.0, 3.8, 2.1], [8.6, 4.0, 2.4]]
print(torch.tensor(array))

print(torch.rand(2, 3).cuda())
torch.rand(2, 3, device="cuda")


tensor([[1.0000, 3.8000, 2.1000],
        [8.6000, 4.0000, 2.4000]])
tensor([[0.5622, 0.6201, 0.7591],
        [0.0494, 0.3269, 0.8518]], device='cuda:0')


tensor([[0.7852, 0.5192, 0.2731],
        [0.8963, 0.2708, 0.4607]], device='cuda:0')

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.double)

print(x.mean(dim=0))
print(x.mean(dim=1))

tensor([2.5000, 3.5000, 4.5000], dtype=torch.float64)
tensor([2., 5.], dtype=torch.float64)


In [14]:
x = torch.tensor([[1, 2, 3], [ 4,  5,  6]], dtype=torch.double)
y = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.double)

torch.cat((x,y),dim=1)

tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]], dtype=torch.float64)

In [15]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.transpose(0,1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [16]:
x = torch.tensor([[[1, 2, 3], [4, 5, 6]]])

x = x.permute(2,0,1)
print(x.shape)

torch.Size([3, 1, 2])


In [18]:
a = torch.tensor([1, 2, 3, 4])

b = a.unsqueeze(dim=0)
print(b,b.shape)

tensor([[1, 2, 3, 4]]) torch.Size([1, 4])
