torch.matmul 适合所有的 支持广播机制

torch.dot 算两个一维张量（即向量）之间的点乘（内积）的函数，不支持广播机制
torch.mm 只支持两个二维矩阵相乘 不支持广播机制
torch.bmm 只支持两个三维矩阵相乘 不支持广播机制

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = torch.dot(a, b)
print(result)

result2 = a @ b
print(result2)

tensor(32)
tensor(32)


In [4]:
x = torch.randn(2, 3)
y = torch.randn(3, 4)
result3 = torch.matmul(x, y)
print(result3)

result4 = torch.mm(x, y)
print(result4)

tensor([[ 3.3295,  0.0638, -0.2572, -3.0442],
        [-0.8862,  0.3887,  0.4263,  1.6469]])
tensor([[ 3.3295,  0.0638, -0.2572, -3.0442],
        [-0.8862,  0.3887,  0.4263,  1.6469]])


In [5]:
x = torch.randn(2, 3, 4)
y = torch.randn(2, 4, 3)
result5 = torch.matmul(x, y)
print(result5)
result6 = torch.bmm(x, y)
print(result6)

tensor([[[ 0.6533,  1.3021,  0.9740],
         [ 0.0332,  0.3360, -0.7595],
         [-0.0926, -0.0469, -0.9199]],

        [[-0.6666,  2.7202, -0.5066],
         [-2.9779,  0.9197, -1.5100],
         [-0.5301,  2.3702,  0.4070]]])
tensor([[[ 0.6533,  1.3021,  0.9740],
         [ 0.0332,  0.3360, -0.7595],
         [-0.0926, -0.0469, -0.9199]],

        [[-0.6666,  2.7202, -0.5066],
         [-2.9779,  0.9197, -1.5100],
         [-0.5301,  2.3702,  0.4070]]])


In [8]:
import torch

# 示例 1: 相同形状的张量的元素级乘法
A = torch.tensor([1, 2, 3])
B = torch.tensor([4, 5, 6])
result = torch.mul(A, B)
print(result)  # 输出: tensor([ 4, 10, 18])

print(A * B)  # 也可以使用 * 运算符进行元素级乘法

# 示例 2: 不同形状的张量进行广播后的元素级乘法
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
B = torch.tensor([10, 20, 30])
result = torch.mul(A, B)
print(result)  # 输出: tensor([[10, 40, 90], [40, 100, 180]])

# 示例 3: 通过标量进行元素级乘法
A = torch.tensor([1, 2, 3])
result = torch.mul(A, 10)
print(result)  # 输出: tensor([10, 20, 30])

tensor([ 4, 10, 18])
tensor([ 4, 10, 18])
tensor([[ 10,  40,  90],
        [ 40, 100, 180]])
tensor([10, 20, 30])
